name = "Diffractor"
uuid = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
authors = ["Keno Fischer <keno@juliacomputing.com> and contributors"]
version = "0.1.1"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
ChainRules = "1.44.6"
ChainRulesCore = "1.15.3"
Combinatorics = "1"
Cthulhu = "2"
OffsetArrays = "1"
PrecompileTools = "1"
StaticArrays = "1"
StatsBase = "0.33, 0.34"
StructArrays = "0.6"
julia = "1.10"
